export const RATE_LIMITS = {
  ASSESSMENT_SOURCE_MAX_ATTEMPTS: 30,
  ASSESSMENT_SOURCE_WINDOW_SECONDS: 3600,
  ASSESSMENT_PHONE_MAX_SUBMISSIONS: 5,
  ASSESSMENT_PHONE_WINDOW_SECONDS: 86400,
} as const;

export const ASSESSMENT_SOURCE_RATE_LIMIT = RATE_LIMITS.ASSESSMENT_SOURCE_MAX_ATTEMPTS;
export const ASSESSMENT_SOURCE_WINDOW_SECONDS =
  RATE_LIMITS.ASSESSMENT_SOURCE_WINDOW_SECONDS;
export const ASSESSMENT_PHONE_RATE_LIMIT = RATE_LIMITS.ASSESSMENT_PHONE_MAX_SUBMISSIONS;
export const ASSESSMENT_PHONE_WINDOW_SECONDS =
  RATE_LIMITS.ASSESSMENT_PHONE_WINDOW_SECONDS;
export const ASSESSMENT_RATE_LIMIT_KEY_PREFIX = "assessment:rl:" as const;
